"""empty message

Revision ID: 3f52cb41ff70
Revises: aec55ffe1c69
Create Date: 2025-04-06 15:04:28.964177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f52cb41ff70'
down_revision = 'aec55ffe1c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('check_out', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')

    # ### end Alembic commands ###
