"""empty message

Revision ID: 4880db0c825f
Revises: 8c994b4a340e
Create Date: 2025-04-14 21:31:39.863782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4880db0c825f'
down_revision = '8c994b4a340e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Rooms', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
