"""empty message

Revision ID: 93d7dc14a839
Revises: b1037befa5c5
Create Date: 2025-04-12 23:10:05.522774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d7dc14a839'
down_revision = 'b1037befa5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['id'])

    # ### end Alembic commands ###
