"""empty message

Revision ID: a4fcb54ff2cc
Revises: a702d17dd6b5
Create Date: 2025-04-13 12:14:58.499674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fcb54ff2cc'
down_revision = 'a702d17dd6b5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                sa.String(length=20),  
                nullable=False,
                server_default='ACTIVE'  
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
