"""empty message

Revision ID: b1037befa5c5
Revises: a819ae38dc49
Create Date: 2025-04-12 12:31:13.078892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1037befa5c5'
down_revision = 'a819ae38dc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Rooms', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('SINGLE', 'DOUBLE', 'SUITE', name='roomtype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Rooms', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('SINGLE', 'DOUBLE', 'SUITE', name='roomtype'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
