"""empty message

Revision ID: bebe00b3aaf9
Revises: 3f52cb41ff70
Create Date: 2025-04-12 01:48:45.147099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebe00b3aaf9'
down_revision = '3f52cb41ff70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('issued_at',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('check_in',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('check_out',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('check_out',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('check_in',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('issued_at',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
